### ISSUE TITLE
Use luasnip for snippet expansion

### ISSUE THREAD

**Issue by clason** [mfussenegger/nvim-lsp-compl#4]
The following setting provides LSP snippet expansion via https://github.com/L3MON4D3/LuaSnip:
```lua
require('lsp_compl').apply_snippet = function(item, suffix)
  if item.textEdit then
    require'luasnip'.lsp_expand(item.textEdit.newText .. suffix)
  elseif item.insertText then
    require'luasnip'.lsp_expand(item.insertText .. suffix)
  end
end
```
This could be mentioned in the README (instead of the `vsnip` config that is the default). Since LuaSnip is getting some traction (and is pure Lua ;)), it might also make sense to take that as the default config?

**Comment by mfussenegger** [comment]
Could you try https://github.com/mfussenegger/nvim-lsp-compl/pull/6 ?

**Comment by clason** [comment]
Yep, that works for me!
